# Generated by Django 5.2.8 on 2025-11-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text="Optional name as listed by the vendor (e.g. 'AP Flour 50lb Bag')", max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Package size (e.g. 5000 for 5kg)', max_digits=10)),
                ('unit', models.CharField(help_text="Unit for the package size, e.g. 'g', 'ml', 'units'", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for the whole package', max_digits=10)),
                ('sku', models.CharField(blank=True, help_text='Optional vendor SKU / code', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='core.ingredient')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'ingredient', 'quantity', 'unit')},
            },
        ),
    ]
